# Generated by Django 3.2.8 on 2021-10-20 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programadores', models.CharField(choices=[('1', 'Pedro'), ('2', 'Juan'), ('3', 'Carlos'), ('4', 'Juanita'), ('5', 'Antonio'), ('6', 'Carolina'), ('7', 'Manuel')], max_length=50)),
                ('modulo', models.CharField(choices=[('1', 'Nómina'), ('2', 'Facturación'), ('3', 'Recibos'), ('4', 'Comprobante contable'), ('5', 'Usuarios'), ('6', 'Contabilidad')], max_length=50)),
                ('t_error', models.CharField(choices=[('1', '404'), ('2', 'Stack overflow'), ('3', 'Memory out of range'), ('4', 'Null pointer'), ('5', 'Syntax error'), ('6', 'Encoding error')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'Carta',
                'verbose_name_plural': 'Cartas',
            },
        ),
    ]
