# Generated by Django 3.2.8 on 2021-10-21 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='carta_repetida',
            field=models.CharField(default='juanito', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cartas_Completas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_carta', models.ImageField(blank=True, upload_to='Cartas_Completas')),
                ('cartas_jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartas.carta')),
            ],
        ),
    ]
