# Generated by Django 3.2.8 on 2021-10-21 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0002_auto_20211021_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartas_completas',
            options={'verbose_name': 'Cartas Completas', 'verbose_name_plural': 'Cartas Completas'},
        ),
    ]
