# Generated by Django 3.2.8 on 2021-10-21 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0004_alter_cartas_completas_cartas_jugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartas_completas',
            name='cartas_jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartas.carta'),
        ),
    ]
