# Generated by Django 3.2.8 on 2021-10-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0006_remove_cartas_completas_cartas_jugador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartas_Completas',
        ),
    ]
