# Generated by Django 3.2.8 on 2021-10-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0008_cartas_completas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartas_completas',
            name='cartas_jugador',
        ),
    ]
