# Generated by Django 3.2.8 on 2021-10-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0009_remove_cartas_completas_cartas_jugador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carta',
            options={'verbose_name': 'Cartas_jugador', 'verbose_name_plural': 'Cartas'},
        ),
    ]
