# Generated by Django 3.2.8 on 2021-10-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0011_alter_carta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carta',
            options={'verbose_name': 'Cartas_jugador', 'verbose_name_plural': 'Cartas jugadores'},
        ),
    ]
