# Generated by Django 3.2.8 on 2021-10-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activo',
            field=models.BooleanField(),
        ),
    ]
